@startuml PC_ARDUINO

participant "PC" as pc
participant "Arduino" as arduino

== Connection ==
pc -> arduino : ping
arduino -> pc : ack

== State updates ==
pc -> arduino : detected
pc -> arduino : not_detected

pc -> arduino : calibration_on
pc -> arduino : calibration_off

== Disconnection ==
pc -> arduino : disconnect
arduino -> pc : ack

@enduml